config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :experiences do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index]
  get "profile", action: :show, controller: "users"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :experience
  validates :date, presence: true
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :name, presence: true
  validates :address, presence: true
  validates :content, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :experiences
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :destroy]

  def index
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_params)
    raise
    @booking.user = current_user
    if @booking.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def new
    @booking = Booking.new
  end

  def destroy
    @booking.destroy
    redirect_to experience_bookings_path
  end

  def show
  end


#Can we just let them cancel? We don't want to let them amend. How to just cancel?

  # def update
  #   @booking.update(booking_params)
  #   redirect_to booking_path(@booking)
  # end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:experience_id, :date, :number_of_participants)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      @experiences = Experience.where("name LIKE ?","%#{params[:query]}%")
      # Preventing SQL Injection and Database error for
      # unknown characters
    else
      @experiences = Experience.all
    end
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    if @experience.save
      redirect_to experiences_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
  end

  def edit
  end

  def update
    @experience.update(experience_params)
    redirect_to experience_path(@experience)
  end

  def destroy
    @experience.destroy
    redirect_to experiences_path
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:name, :content, :price, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @bookings = current_user.bookings
    @experiences = current_user.experiences
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Experiences#create</h1>
<p>Find me in app/views/Experiences/create.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

#

app/views/experiences/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/experiences/index.html.erb
<%# <h1>All Experiences</h1>

<% @experiences.each do |experience|%>
<%# <h5> <%= experience.name %>
<%# <p> <%= experience.content %>
<%# <%= experience.price %>
<%# <%= experience.picture_url %>
<%# <% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>All dating experiences</h1>
      <div class="search-bar-index">
      <form action="/experiences" accept-charset="UTF-8" method="get">
      
      <input type="text" name="query" id="form-placeholder" class="form control form-search" placeholder="Find an experience..."><input type="submit" name="commit" value="Search" class="btn-search btn-search-index btn-experience-new" data-disable-with="Search">
</form> 
</div>
</div>
</div>
<div class="container">
      <ul class="list-group">
        <% @experiences.each do |experience| %>
  <%# <h2>Search our experiences below...</h2> %>
  <div class="card-trip">
  <%= [image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644665936/tate_britain_exterior_1_yyyfwz.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669175/shard_fasbdu.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669328/ronniescott_ewcbxt.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669478/lapland_c1xjmh.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669676/pizzaeast_j438iw.jpg"),
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669765/eastville_h3xbsi.png")].sample %>
  <%# <%= img src="https://www.tate.org.uk/sites/default/files/styles/width-600/public/tate_britain_exterior_1.jpg" %>
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to experience.name, experience_path(experience) %></h2>
      <p><%= experience.content %></p>
    </div>
    <h2 class="card-trip-pricing">Top ranking</h2>
  </div>
  <div class="card-trip">
  <%= [image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644665936/tate_britain_exterior_1_yyyfwz.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669175/shard_fasbdu.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669328/ronniescott_ewcbxt.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669478/lapland_c1xjmh.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669676/pizzaeast_j438iw.jpg"),
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669765/eastville_h3xbsi.png")].sample %>
  <%# <%= img src="https://www.tate.org.uk/sites/default/files/styles/width-600/public/tate_britain_exterior_1.jpg" %>
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to experience.name, experience_path(experience) %></h2>
      <p><%= experience.content %></p>
    </div>
    <h2 class="card-trip-pricing">Top ranking</h2>
  </div>
   <div class="card-trip">
  <%= [image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644665936/tate_britain_exterior_1_yyyfwz.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669175/shard_fasbdu.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669328/ronniescott_ewcbxt.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669478/lapland_c1xjmh.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669676/pizzaeast_j438iw.jpg"),
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669765/eastville_h3xbsi.png")].sample %>
  <%# <%= img src="https://www.tate.org.uk/sites/default/files/styles/width-600/public/tate_britain_exterior_1.jpg" %>
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to experience.name, experience_path(experience) %></h2>
      <p><%= experience.content %></p>
    </div>
    <h2 class="card-trip-pricing">Top ranking</h2>
  </div>
   <div class="card-trip">
  <%= [image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644665936/tate_britain_exterior_1_yyyfwz.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669175/shard_fasbdu.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669328/ronniescott_ewcbxt.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669478/lapland_c1xjmh.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669676/pizzaeast_j438iw.jpg"),
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669765/eastville_h3xbsi.png")].sample %>
  <%# <%= img src="https://www.tate.org.uk/sites/default/files/styles/width-600/public/tate_britain_exterior_1.jpg" %>
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to experience.name, experience_path(experience) %></h2>
      <p><%= experience.content %></p>
    </div>
    <h2 class="card-trip-pricing">Top ranking</h2>
  </div>
   <div class="card-trip">
  <%= [image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644665936/tate_britain_exterior_1_yyyfwz.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669175/shard_fasbdu.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669328/ronniescott_ewcbxt.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669478/lapland_c1xjmh.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669676/pizzaeast_j438iw.jpg"),
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669765/eastville_h3xbsi.png")].sample %>
  <%# <%= img src="https://www.tate.org.uk/sites/default/files/styles/width-600/public/tate_britain_exterior_1.jpg" %>
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to experience.name, experience_path(experience) %></h2>
      <p><%= experience.content %></p>
    </div>
    <h2 class="card-trip-pricing">Top ranking</h2>
  </div>
   <div class="card-trip">
  <%= [image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644665936/tate_britain_exterior_1_yyyfwz.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669175/shard_fasbdu.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669328/ronniescott_ewcbxt.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669478/lapland_c1xjmh.jpg"), 
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669676/pizzaeast_j438iw.jpg"),
       image_tag("https://res.cloudinary.com/dfljjticx/image/upload/v1644669765/eastville_h3xbsi.png")].sample %>
  <%# <%= img src="https://www.tate.org.uk/sites/default/files/styles/width-600/public/tate_britain_exterior_1.jpg" %>
  <div class="card-trip-infos">
    <div>
      <h2><%= link_to experience.name, experience_path(experience) %></h2>
      <p><%= experience.content %></p>
    </div>
    <h2 class="card-trip-pricing">Top ranking</h2>
  </div>
    </div>
   </div>
  </div>
 </div>
 </ul>
<% end %>
<div>
      <%= link_to "Add a new Experience", new_experience_path, class: 'btn btn-primary' %>
      </div>
    

app/views/experiences/new.html.erb
<h1>Experiences#new</h1>
<p>Find me in app/views/Experiences/new.html.erb</p>

app/views/experiences/show.html.erb
<div class="experiences-container">
  <div class="row">
   <div class="title">
      <h1><%= @experience.name %></h1>
      <h3><%= @experience.content %></h3>
      <h3>£<%= @experience.price %></h3>
      <%= image_tag "https://www.tate.org.uk/sites/default/files/styles/width-600/public/tate_britain_exterior_1.jpg" %>
      <div class="row">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        </div>
      </div>
    </div>
  </div>
  <div class="col-5">
    <div class="booking-form">
       <h3>BOOKING</h3>
      <div class="fields">
      <%= simple_form_for([ @experience, @booking ]) do |f| %>
        <%= f.input :date, as: :date, html5: true %>
        <%= f.input :number_of_participants, as: :integer %>
        <%# <%= f.button :submit %>
        <% end %>

       <%# <form class = "simple_form new_booking" id="new_booking" novalidate="novalidate" action="experiences/1/bookings" accept-charset="UTF-8" method="post">
          <input type="hidden" name="authenticity_token" value="mSiWdmcYEm/SA1QmjSexwT8HCxS+23pFtItdqoufdjh1WM555Eu/RjaFrA5j5NoZz/latc1LEmjX/u488pDSKA==">
          <div class="form-group date required booking_date">
            <label class="date required" for="booking_date">
               Date
            </label>
            <div class="d-flex flex-row justify-content-between align-items-center">
              <input class="form-control mx-1 date required" type="date" name="booking[date]" id="booking_date">
            </div>
          </div>
          <div class="form-group integer required booking_number_of_people">
            <label class="integer required" for="booking_number_of_people">
              Number of people
            </label>
            <input class="form-control numeric integer required inline-element" type="number" step="1" name="booking[number_of_people]" id="booking_number_of_people">
          </div>

          <%# <input type="submit" name="commit" value="Book" class="btn-search btn-search-index btn-island-new" data-disable-with="Book"> %>
          <%= link_to "Book", "/profile", class: "button/bookings" %>

       </form>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dating Experiences</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="front-page">
  <%= video_tag "dating.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video" %>
</div>

<div class= "homepage_wrapper">
<div class="homepage-text">
  <%# <h1>PICK A DATE</h1> %>
  <p>BOOK YOUR MOST MEMORABLE DATING EXPERIENCE YET</p>
</div>


<%= link_to "Take me to Dating Experiences", "/experiences", class: "button" %>
</div>

<%# <%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <%# <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn_btn_flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>


<%# <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div> %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "heart.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Experiences", "/experiences", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://media-exp1.licdn.com/dms/image/C4D03AQEeDt__IceKgA/profile-displayphoto-shrink_800_800/0/1610963974924?e=1649894400&v=beta&t=ce2kruwF7C1QNxjI9i9yp5lyLyXgXVyjuo8X_R8igZA", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", "/profile", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item"%>
            </div>
          </li>
        <%# <% else %>
          <!--li class="nav-item"-->
            <%# <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%# <%# <% @bookings.each do |booking|
<%# <<%= booking %>
<%# <% end %>

<%#
<div class="bookings">
      <h3 class="sub-heading">YOUR BOOKINGS</h3>
      <div class="row">
        <div class="col-md-4">
          <div class="card-trip-infos">
              <img src="https://www.tate.org.uk/sites/default/files/styles/width-720/public/images/people-on-the-millennium-br_0.jpg">
            <div class="card-product-infos">
              <h4><a href="/experiences/2">DATE AT THE TATE</a></h4>
              <p>Booked on Feb 13</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card-trip-infos">
              <img src="https://cdn.londonandpartners.com/-/media/images/london/visit/things-to-do/nightlife/279177-ronnie-scotts-640x360.jpg?mw=640&hash=96AF3BCA8A353C22BA20FF074F584587BAADC2CE">
            <div class="card-product-infos">
              <h4><a href="/experiences/3">RONNIE SCOTT</a></h4>
              <p>Booked on Jan 4</p>
            </div>
          </div>
        </div>
        <!-- <div class="col-md-4">
        </div>
        <div class="col-md-4">
        </div> -->
      </div>
    </div> %>

<div class="bookings">
   <h3 class="sub-heading">YOUR BOOKINGS</h3>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="card-trip">
              <img src="https://www.tate.org.uk/sites/default/files/styles/width-720/public/images/people-on-the-millennium-br_0.jpg">
              <div class="card-trip-infos">
                <div>
                <h4>DATE AT THE TATE</h4>
                  <h5>Booked on Feb 14</h5>
                </div>
                  <%= link_to "Book again?", "/experiences", class: "button-profile" %>
              </div>
          </div>
          <div class="card-trip">
            <img src="https://cdn.londonandpartners.com/-/media/images/london/visit/things-to-do/nightlife/279177-ronnie-scotts-640x360.jpg?mw=640&hash=96AF3BCA8A353C22BA20FF074F584587BAADC2CE">
            <div class="card-trip-infos">
            <div>
            <h4>RONNIE SCOTT</h4>
              <h5>Booked on Jan 4</h5>
            </div>
            <%= link_to "Book again?", "/experiences", class: "button-profile" %>
            </div>
          </div>
        </div>
      </div>
    </div>
   </div>


<%# image_tag "https://www.tate.org.uk/sites/default/files/styles/width-720/public/images/people-on-the-millennium-br_0.jpg" %>